import '../styles/globals.css'
import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'

const prompt = Prompt({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin', 'thai'],
  variable: '--font-prompt',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th" data-theme="business" className={`${prompt.variable}`}>
      <body className="font-prompt">{children}</body>
    </html>
  )
}